insert into test.groups (name) values ('Группа 1');
insert into test.groups (name) values ('Группа 2');
insert into test.groups (name) values ('Группа 3');
insert into test.groups (name) values ('Группа 4');
insert into test.groups (name) values ('Группа 5');
insert into test.groups (name) values ('Группа 6');
insert into test.groups (name) values ('Группа 7');
insert into test.groups (name) values ('Группа 8');
insert into test.groups (name) values ('Группа 9');
insert into test.groups (name) values ('Группа 10');

insert into test.students (name, group_id) VALUES ('Боря - 1',7);
insert into test.students (name, group_id) VALUES ('Боря - 2',8);
insert into test.students (name, group_id) VALUES ('Боря - 3',5);
insert into test.students (name, group_id) VALUES ('Боря - 4',1);
insert into test.students (name, group_id) VALUES ('Боря - 5',1);
insert into test.students (name, group_id) VALUES ('Боря - 6',10);
insert into test.students (name, group_id) VALUES ('Боря - 7',1);
insert into test.students (name, group_id) VALUES ('Боря - 8',2);
insert into test.students (name, group_id) VALUES ('Боря - 9',5);
insert into test.students (name, group_id) VALUES ('Боря - 10',3);
insert into test.students (name, group_id) VALUES ('Саша - 1',3);
insert into test.students (name, group_id) VALUES ('Саша - 2',8);
insert into test.students (name, group_id) VALUES ('Саша - 3',8);
insert into test.students (name, group_id) VALUES ('Саша - 4',1);
insert into test.students (name, group_id) VALUES ('Саша - 5',4);
insert into test.students (name, group_id) VALUES ('Саша - 6',9);
insert into test.students (name, group_id) VALUES ('Саша - 7',1);
insert into test.students (name, group_id) VALUES ('Саша - 8',9);
insert into test.students (name, group_id) VALUES ('Саша - 9',1);
insert into test.students (name, group_id) VALUES ('Саша - 10',10);
insert into test.students (name, group_id) VALUES ('Маша - 1',4);
insert into test.students (name, group_id) VALUES ('Маша - 2',2);
insert into test.students (name, group_id) VALUES ('Маша - 3',6);
insert into test.students (name, group_id) VALUES ('Маша - 4',9);
insert into test.students (name, group_id) VALUES ('Маша - 5',2);
insert into test.students (name, group_id) VALUES ('Маша - 6',4);
insert into test.students (name, group_id) VALUES ('Маша - 7',5);
insert into test.students (name, group_id) VALUES ('Маша - 8',4);
insert into test.students (name, group_id) VALUES ('Маша - 9',9);
insert into test.students (name, group_id) VALUES ('Маша - 10',7);
insert into test.students (name, group_id) VALUES ('Даша - 1',8);
insert into test.students (name, group_id) VALUES ('Даша - 2',5);
insert into test.students (name, group_id) VALUES ('Даша - 3',8);
insert into test.students (name, group_id) VALUES ('Даша - 4',4);
insert into test.students (name, group_id) VALUES ('Даша - 5',5);
insert into test.students (name, group_id) VALUES ('Даша - 6',6);
insert into test.students (name, group_id) VALUES ('Даша - 7',2);
insert into test.students (name, group_id) VALUES ('Даша - 8',8);
insert into test.students (name, group_id) VALUES ('Даша - 9',9);
insert into test.students (name, group_id) VALUES ('Даша - 10',8);
insert into test.students (name, group_id) VALUES ('Клава - 1',9);
insert into test.students (name, group_id) VALUES ('Клава - 2',5);
insert into test.students (name, group_id) VALUES ('Клава - 3',6);
insert into test.students (name, group_id) VALUES ('Клава - 4',5);
insert into test.students (name, group_id) VALUES ('Клава - 5',9);
insert into test.students (name, group_id) VALUES ('Клава - 6',9);
insert into test.students (name, group_id) VALUES ('Клава - 7',9);
insert into test.students (name, group_id) VALUES ('Клава - 8',10);
insert into test.students (name, group_id) VALUES ('Клава - 9',6);
insert into test.students (name, group_id) VALUES ('Клава - 10',8);
insert into test.students (name, group_id) VALUES ('Олег - 1',4);
insert into test.students (name, group_id) VALUES ('Олег - 2',10);
insert into test.students (name, group_id) VALUES ('Олег - 3',1);
insert into test.students (name, group_id) VALUES ('Олег - 4',3);
insert into test.students (name, group_id) VALUES ('Олег - 5',7);
insert into test.students (name, group_id) VALUES ('Олег - 6',9);
insert into test.students (name, group_id) VALUES ('Олег - 7',7);
insert into test.students (name, group_id) VALUES ('Олег - 8',6);
insert into test.students (name, group_id) VALUES ('Олег - 9',2);
insert into test.students (name, group_id) VALUES ('Олег - 10',8);
insert into test.students (name, group_id) VALUES ('Миша - 1',5);
insert into test.students (name, group_id) VALUES ('Миша - 2',6);
insert into test.students (name, group_id) VALUES ('Миша - 3',3);
insert into test.students (name, group_id) VALUES ('Миша - 4',1);
insert into test.students (name, group_id) VALUES ('Миша - 5',8);
insert into test.students (name, group_id) VALUES ('Миша - 6',7);
insert into test.students (name, group_id) VALUES ('Миша - 7',5);
insert into test.students (name, group_id) VALUES ('Миша - 8',8);
insert into test.students (name, group_id) VALUES ('Миша - 9',6);
insert into test.students (name, group_id) VALUES ('Миша - 10',7);
insert into test.students (name, group_id) VALUES ('Костя - 1',6);
insert into test.students (name, group_id) VALUES ('Костя - 2',3);
insert into test.students (name, group_id) VALUES ('Костя - 3',8);
insert into test.students (name, group_id) VALUES ('Костя - 4',5);
insert into test.students (name, group_id) VALUES ('Костя - 5',4);
insert into test.students (name, group_id) VALUES ('Костя - 6',8);
insert into test.students (name, group_id) VALUES ('Костя - 7',5);
insert into test.students (name, group_id) VALUES ('Костя - 8',9);
insert into test.students (name, group_id) VALUES ('Костя - 9',7);
insert into test.students (name, group_id) VALUES ('Костя - 10',7);
insert into test.students (name, group_id) VALUES ('Андрей - 1',9);
insert into test.students (name, group_id) VALUES ('Андрей - 2',2);
insert into test.students (name, group_id) VALUES ('Андрей - 3',9);
insert into test.students (name, group_id) VALUES ('Андрей - 4',8);
insert into test.students (name, group_id) VALUES ('Андрей - 5',4);
insert into test.students (name, group_id) VALUES ('Андрей - 6',6);
insert into test.students (name, group_id) VALUES ('Андрей - 7',6);
insert into test.students (name, group_id) VALUES ('Андрей - 8',7);
insert into test.students (name, group_id) VALUES ('Андрей - 9',3);
insert into test.students (name, group_id) VALUES ('Андрей - 10',9);
insert into test.students (name, group_id) VALUES ('Алексей - 1',3);
insert into test.students (name, group_id) VALUES ('Алексей - 2',10);
insert into test.students (name, group_id) VALUES ('Алексей - 3',6);
insert into test.students (name, group_id) VALUES ('Алексей - 4',10);
insert into test.students (name, group_id) VALUES ('Алексей - 5',8);
insert into test.students (name, group_id) VALUES ('Алексей - 6',4);
insert into test.students (name, group_id) VALUES ('Алексей - 7',3);
insert into test.students (name, group_id) VALUES ('Алексей - 8',10);
insert into test.students (name, group_id) VALUES ('Алексей - 9',5);
insert into test.students (name, group_id) VALUES ('Алексей - 10',10);

